language: cpp
sudo: required
dist: trusty

addons:
    apt:
        sources:
            - ubuntu-sdk-team
        packages:
            - qt5-qmake
            - qtbase5-dev
            - qtdeclarative5-dev
            - libqt5opengl5-dev

script:
    - qmake -qt=qt5 -v
    - qmake -qt=qt5
    - make
